name = "bookee"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[[ d1_databases ]]
binding = "DB"
database_name = "bookee"
database_id = "0bc9b401-7e20-4378-a519-a2e485506a3d"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "945d366efdaf401ba8c1455cc53f8735"
preview_id = "af777d7068df4172b7717048407c8565"

# kv_namespaces = [
#   { binding = "SESSION_KV", id = "945d366efdaf401ba8c1455cc53f8735", preview_id = "af777d7068df4172b7717048407c8565" }
# ]
